### ISSUE TITLE
Is this really using version 51 of weasyprint?

### ISSUE THREAD

**Issue by espechtcfe** [aquavitae/docker-weasyprint#14]
When I look in the requirements.txt file, I see that the weasyprint version is specified as version 51, which is what I hoped.  However, when I start an interactive session using the following:
docker run -it -p 5001:5001 aquavitae/weasyprint /bin/bash

Then if I run the following command:
weasyprint --version
I get the following:
WeasyPrint version 0.31

Shouldn't I be seeing version 51 there?

**Comment by samjetski** [comment]
Hi @espechtcfe, unfortunately the [version published on Docker Hub](https://hub.docker.com/r/aquavitae/weasyprint) is quite a bit behind. #11 would fix this but could be a while off (depending on @aquavitae's availability?).

In the meantime, you can get the latest version by cloning this repository and building the image directly. This also gives you the opportunity to bump to a newer Weasyprint version if you wish.

```bash
sed -i 's/WeasyPrint==51/WeasyPrint==52.2/g' requirements.txt
docker build -t weasyprint:52.2 .
docker run --rm -it weasyprint:52.2 weasyprint --version
```

We made a few other changes and pushed it to a private container registry to make it easier to direct-run and deploy on our infrastructure. We're using Azure/ACR, but GitLab.com is a good free option if you need this, i.e. `docker run registry.gitlab.com/youraccount/weasyprint:52.2`.
