### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by vojkny** [aquavitae/docker-weasyprint#9]
Can you confirm how the logs coming from weasyprint are processed? It seems to me all of them are hidden and we just get logs from gunicorn. Is there a way to reveal those? Is weasyprint's logging compatibble with the gunicorn logging?

**Comment by stuaxo** [comment]
Hi,
   Look into weasyprints loggers.   as a starting point, I was able to get some weasyprint to log to stderr, using the code below.

I haven't yet tested this in the flask app here.

```python
logger = logging.getLogger('weasyprint')

handler = logging.StreamHandler(sys.stderr)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    level=logging.INFO,
    datefmt='%Y-%m-%d %H:%M:%S')
```
